name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose up -d --build
          sleep 10  # Wait for services to be ready

      - name: Test /ping endpoint
        run: |
          curl --fail http://localhost:5000/ping

      - name: Test /users endpoint
        run: |
          curl --fail http://localhost:5000/users

      - name: Shutdown
        run: docker compose down
