apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-agriculture-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Jnr-Neba/smart_agriculture_project"
    targetRevision: HEAD
    path: terraform-configs/argocd-app.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
